/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'status' : CandidateStatus,
  'source' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'email' : string,
  'updatedAt' : bigint,
  'notes' : string,
  'phone' : string,
  'skills' : string,
  'jobOpeningId' : [] | [bigint],
}
export type CandidateStatus = { 'new' : null } |
  { 'placed' : null } |
  { 'screening' : null } |
  { 'rejected' : null } |
  { 'interviewing' : null } |
  { 'offered' : null };
export interface Client {
  'id' : bigint,
  'status' : EntityStatus,
  'createdAt' : bigint,
  'contactPerson' : string,
  'email' : string,
  'updatedAt' : bigint,
  'address' : string,
  'notes' : string,
  'companyName' : string,
  'phone' : string,
}
export type EntityStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Interview {
  'id' : bigint,
  'status' : InterviewStatus,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'interviewDate' : bigint,
  'interviewType' : InterviewType,
  'outcome' : string,
  'candidateId' : bigint,
  'location' : string,
  'jobOpeningId' : [] | [bigint],
  'interviewerName' : string,
}
export type InterviewStatus = { 'scheduled' : null } |
  { 'noShow' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type InterviewType = { 'video' : null } |
  { 'phone' : null } |
  { 'inPerson' : null };
export interface JobOpening {
  'id' : bigint,
  'status' : JobStatus,
  'title' : string,
  'clientId' : [] | [bigint],
  'salary' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'requirements' : string,
  'location' : string,
}
export type JobStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'paused' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCandidate' : ActorMethod<
    [string, string, string, string, string, string, [] | [bigint]],
    bigint
  >,
  'createClient' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'createInterview' : ActorMethod<
    [bigint, [] | [bigint], bigint, InterviewType, string, string],
    bigint
  >,
  'createJobOpening' : ActorMethod<
    [string, [] | [bigint], string, [] | [string], string, string],
    bigint
  >,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInterview' : ActorMethod<[bigint], undefined>,
  'deleteJobOpening' : ActorMethod<[bigint], undefined>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInterviews' : ActorMethod<[], Array<Interview>>,
  'getAllJobOpenings' : ActorMethod<[], Array<JobOpening>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidate' : ActorMethod<[bigint], Candidate>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getInterview' : ActorMethod<[bigint], Interview>,
  'getJobOpening' : ActorMethod<[bigint], JobOpening>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCandidate' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      CandidateStatus,
      [] | [bigint],
    ],
    undefined
  >,
  'updateClient' : ActorMethod<
    [bigint, string, string, string, string, string, string, EntityStatus],
    undefined
  >,
  'updateInterview' : ActorMethod<
    [
      bigint,
      bigint,
      [] | [bigint],
      bigint,
      InterviewType,
      string,
      string,
      InterviewStatus,
      string,
    ],
    undefined
  >,
  'updateJobOpening' : ActorMethod<
    [
      bigint,
      string,
      [] | [bigint],
      string,
      [] | [string],
      string,
      string,
      JobStatus,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];