/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InterviewType = IDL.Variant({
  'video' : IDL.Null,
  'phone' : IDL.Null,
  'inPerson' : IDL.Null,
});
export const CandidateStatus = IDL.Variant({
  'new' : IDL.Null,
  'placed' : IDL.Null,
  'screening' : IDL.Null,
  'rejected' : IDL.Null,
  'interviewing' : IDL.Null,
  'offered' : IDL.Null,
});
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'status' : CandidateStatus,
  'source' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'jobOpeningId' : IDL.Opt(IDL.Nat),
});
export const EntityStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'status' : EntityStatus,
  'staffingRequirements' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const InterviewStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'noShow' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Interview = IDL.Record({
  'id' : IDL.Nat,
  'status' : InterviewStatus,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'interviewDate' : IDL.Int,
  'interviewType' : InterviewType,
  'outcome' : IDL.Text,
  'candidateId' : IDL.Nat,
  'location' : IDL.Text,
  'jobOpeningId' : IDL.Opt(IDL.Nat),
  'interviewerName' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'paused' : IDL.Null,
});
export const JobOpening = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Opt(IDL.Nat),
  'salary' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const ClientWithJobOpenings = IDL.Record({
  'client' : Client,
  'jobOpenings' : IDL.Vec(JobOpening),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'createClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createInterview' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Int, InterviewType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createJobOpening' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInterview' : IDL.Func([IDL.Nat], [], []),
  'deleteJobOpening' : IDL.Func([IDL.Nat], [], []),
  'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getAllJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidate' : IDL.Func([IDL.Nat], [Candidate], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getClientWithJobOpenings' : IDL.Func(
      [IDL.Nat],
      [ClientWithJobOpenings],
      ['query'],
    ),
  'getInterview' : IDL.Func([IDL.Nat], [Interview], ['query']),
  'getJobOpening' : IDL.Func([IDL.Nat], [JobOpening], ['query']),
  'getJobOpeningsForClient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobOpening)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCandidate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        CandidateStatus,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateClient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        EntityStatus,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateInterview' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Int,
        InterviewType,
        IDL.Text,
        IDL.Text,
        InterviewStatus,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateJobOpening' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        JobStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InterviewType = IDL.Variant({
    'video' : IDL.Null,
    'phone' : IDL.Null,
    'inPerson' : IDL.Null,
  });
  const CandidateStatus = IDL.Variant({
    'new' : IDL.Null,
    'placed' : IDL.Null,
    'screening' : IDL.Null,
    'rejected' : IDL.Null,
    'interviewing' : IDL.Null,
    'offered' : IDL.Null,
  });
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'status' : CandidateStatus,
    'source' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'jobOpeningId' : IDL.Opt(IDL.Nat),
  });
  const EntityStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'status' : EntityStatus,
    'staffingRequirements' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InterviewStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'noShow' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Interview = IDL.Record({
    'id' : IDL.Nat,
    'status' : InterviewStatus,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'interviewDate' : IDL.Int,
    'interviewType' : InterviewType,
    'outcome' : IDL.Text,
    'candidateId' : IDL.Nat,
    'location' : IDL.Text,
    'jobOpeningId' : IDL.Opt(IDL.Nat),
    'interviewerName' : IDL.Text,
  });
  const JobStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'paused' : IDL.Null,
  });
  const JobOpening = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Opt(IDL.Nat),
    'salary' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const ClientWithJobOpenings = IDL.Record({
    'client' : Client,
    'jobOpenings' : IDL.Vec(JobOpening),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'createClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createInterview' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Int, InterviewType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createJobOpening' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInterview' : IDL.Func([IDL.Nat], [], []),
    'deleteJobOpening' : IDL.Func([IDL.Nat], [], []),
    'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'getAllJobOpenings' : IDL.Func([], [IDL.Vec(JobOpening)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidate' : IDL.Func([IDL.Nat], [Candidate], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getClientWithJobOpenings' : IDL.Func(
        [IDL.Nat],
        [ClientWithJobOpenings],
        ['query'],
      ),
    'getInterview' : IDL.Func([IDL.Nat], [Interview], ['query']),
    'getJobOpening' : IDL.Func([IDL.Nat], [JobOpening], ['query']),
    'getJobOpeningsForClient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobOpening)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCandidate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          CandidateStatus,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateClient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          EntityStatus,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateInterview' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Int,
          InterviewType,
          IDL.Text,
          IDL.Text,
          InterviewStatus,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateJobOpening' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          JobStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };