/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Interview {
    id: bigint;
    status: InterviewStatus;
    createdAt: bigint;
    updatedAt: bigint;
    interviewDate: bigint;
    interviewType: InterviewType;
    outcome: string;
    candidateId: bigint;
    location: string;
    jobOpeningId?: bigint;
    interviewerName: string;
}
export interface Candidate {
    id: bigint;
    status: CandidateStatus;
    source: string;
    createdAt: bigint;
    fullName: string;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
    skills: string;
    jobOpeningId?: bigint;
}
export interface JobOpening {
    id: bigint;
    status: JobStatus;
    title: string;
    clientId?: bigint;
    salary?: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    requirements: string;
    location: string;
}
export interface Client {
    id: bigint;
    status: EntityStatus;
    createdAt: bigint;
    contactPerson: string;
    email: string;
    updatedAt: bigint;
    address: string;
    notes: string;
    companyName: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum CandidateStatus {
    new_ = "new",
    placed = "placed",
    screening = "screening",
    rejected = "rejected",
    interviewing = "interviewing",
    offered = "offered"
}
export enum EntityStatus {
    active = "active",
    inactive = "inactive"
}
export enum InterviewStatus {
    scheduled = "scheduled",
    noShow = "noShow",
    cancelled = "cancelled",
    completed = "completed"
}
export enum InterviewType {
    video = "video",
    phone = "phone",
    inPerson = "inPerson"
}
export enum JobStatus {
    closed = "closed",
    open = "open",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCandidate(fullName: string, phone: string, email: string, skills: string, notes: string, source: string, jobOpeningId: bigint | null): Promise<bigint>;
    createClient(companyName: string, contactPerson: string, phone: string, email: string, address: string, notes: string): Promise<bigint>;
    createInterview(candidateId: bigint, jobOpeningId: bigint | null, interviewDate: bigint, interviewType: InterviewType, interviewerName: string, location: string): Promise<bigint>;
    createJobOpening(title: string, clientId: bigint | null, location: string, salary: string | null, description: string, requirements: string): Promise<bigint>;
    deleteCandidate(id: bigint): Promise<void>;
    deleteClient(id: bigint): Promise<void>;
    deleteInterview(id: bigint): Promise<void>;
    deleteJobOpening(id: bigint): Promise<void>;
    getAllCandidates(): Promise<Array<Candidate>>;
    getAllClients(): Promise<Array<Client>>;
    getAllInterviews(): Promise<Array<Interview>>;
    getAllJobOpenings(): Promise<Array<JobOpening>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidate(id: bigint): Promise<Candidate>;
    getClient(id: bigint): Promise<Client>;
    getInterview(id: bigint): Promise<Interview>;
    getJobOpening(id: bigint): Promise<JobOpening>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCandidate(id: bigint, fullName: string, phone: string, email: string, skills: string, notes: string, source: string, status: CandidateStatus, jobOpeningId: bigint | null): Promise<void>;
    updateClient(id: bigint, companyName: string, contactPerson: string, phone: string, email: string, address: string, notes: string, status: EntityStatus): Promise<void>;
    updateInterview(id: bigint, candidateId: bigint, jobOpeningId: bigint | null, interviewDate: bigint, interviewType: InterviewType, interviewerName: string, location: string, status: InterviewStatus, outcome: string): Promise<void>;
    updateJobOpening(id: bigint, title: string, clientId: bigint | null, location: string, salary: string | null, description: string, requirements: string, status: JobStatus): Promise<void>;
}
import type { Candidate as _Candidate, CandidateStatus as _CandidateStatus, Client as _Client, EntityStatus as _EntityStatus, Interview as _Interview, InterviewStatus as _InterviewStatus, InterviewType as _InterviewType, JobOpening as _JobOpening, JobStatus as _JobStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInterview(arg0: bigint, arg1: bigint | null, arg2: bigint, arg3: InterviewType, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterview(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_InterviewType_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterview(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_InterviewType_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createJobOpening(arg0: string, arg1: bigint | null, arg2: string, arg3: string | null, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobOpening(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobOpening(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async deleteCandidate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteInterview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInterview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInterview(arg0);
            return result;
        }
    }
    async deleteJobOpening(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobOpening(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobOpening(arg0);
            return result;
        }
    }
    async getAllCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCandidates();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCandidates();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInterviews(): Promise<Array<Interview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInterviews();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInterviews();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobOpenings(): Promise<Array<JobOpening>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobOpenings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobOpenings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidate(arg0: bigint): Promise<Candidate> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidate(arg0);
                return from_candid_Candidate_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidate(arg0);
            return from_candid_Candidate_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_Client_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_Client_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterview(arg0: bigint): Promise<Interview> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterview(arg0);
                return from_candid_Interview_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterview(arg0);
            return from_candid_Interview_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobOpening(arg0: bigint): Promise<JobOpening> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobOpening(arg0);
                return from_candid_JobOpening_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobOpening(arg0);
            return from_candid_JobOpening_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCandidate(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: CandidateStatus, arg8: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_CandidateStatus_n34(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_CandidateStatus_n34(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: EntityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EntityStatus_n36(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EntityStatus_n36(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateInterview(arg0: bigint, arg1: bigint, arg2: bigint | null, arg3: bigint, arg4: InterviewType, arg5: string, arg6: string, arg7: InterviewStatus, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInterview(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_InterviewType_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_InterviewStatus_n38(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInterview(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_InterviewType_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_InterviewStatus_n38(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async updateJobOpening(arg0: bigint, arg1: string, arg2: bigint | null, arg3: string, arg4: string | null, arg5: string, arg6: string, arg7: JobStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobOpening(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_JobStatus_n40(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobOpening(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_JobStatus_n40(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_CandidateStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateStatus): CandidateStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Candidate_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EntityStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityStatus): EntityStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewStatus): InterviewStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewType): InterviewType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Interview_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interview): Interview {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_JobOpening_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobOpening): JobOpening {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EntityStatus;
    createdAt: bigint;
    contactPerson: string;
    email: string;
    updatedAt: bigint;
    address: string;
    notes: string;
    companyName: string;
    phone: string;
}): {
    id: bigint;
    status: EntityStatus;
    createdAt: bigint;
    contactPerson: string;
    email: string;
    updatedAt: bigint;
    address: string;
    notes: string;
    companyName: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_EntityStatus_n16(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        notes: value.notes,
        companyName: value.companyName,
        phone: value.phone
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InterviewStatus;
    createdAt: bigint;
    updatedAt: bigint;
    interviewDate: bigint;
    interviewType: _InterviewType;
    outcome: string;
    candidateId: bigint;
    location: string;
    jobOpeningId: [] | [bigint];
    interviewerName: string;
}): {
    id: bigint;
    status: InterviewStatus;
    createdAt: bigint;
    updatedAt: bigint;
    interviewDate: bigint;
    interviewType: InterviewType;
    outcome: string;
    candidateId: bigint;
    location: string;
    jobOpeningId?: bigint;
    interviewerName: string;
} {
    return {
        id: value.id,
        status: from_candid_InterviewStatus_n21(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        interviewDate: value.interviewDate,
        interviewType: from_candid_InterviewType_n23(_uploadFile, _downloadFile, value.interviewType),
        outcome: value.outcome,
        candidateId: value.candidateId,
        location: value.location,
        jobOpeningId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.jobOpeningId)),
        interviewerName: value.interviewerName
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    title: string;
    clientId: [] | [bigint];
    salary: [] | [string];
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    requirements: string;
    location: string;
}): {
    id: bigint;
    status: JobStatus;
    title: string;
    clientId?: bigint;
    salary?: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.clientId)),
        salary: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.salary)),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CandidateStatus;
    source: string;
    createdAt: bigint;
    fullName: string;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
    skills: string;
    jobOpeningId: [] | [bigint];
}): {
    id: bigint;
    status: CandidateStatus;
    source: string;
    createdAt: bigint;
    fullName: string;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
    skills: string;
    jobOpeningId?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CandidateStatus_n10(_uploadFile, _downloadFile, value.status),
        source: value.source,
        createdAt: value.createdAt,
        fullName: value.fullName,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone,
        skills: value.skills,
        jobOpeningId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.jobOpeningId))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    placed: null;
} | {
    screening: null;
} | {
    rejected: null;
} | {
    interviewing: null;
} | {
    offered: null;
}): CandidateStatus {
    return "new" in value ? CandidateStatus.new : "placed" in value ? CandidateStatus.placed : "screening" in value ? CandidateStatus.screening : "rejected" in value ? CandidateStatus.rejected : "interviewing" in value ? CandidateStatus.interviewing : "offered" in value ? CandidateStatus.offered : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): EntityStatus {
    return "active" in value ? EntityStatus.active : "inactive" in value ? EntityStatus.inactive : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    noShow: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): InterviewStatus {
    return "scheduled" in value ? InterviewStatus.scheduled : "noShow" in value ? InterviewStatus.noShow : "cancelled" in value ? InterviewStatus.cancelled : "completed" in value ? InterviewStatus.completed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    phone: null;
} | {
    inPerson: null;
}): InterviewType {
    return "video" in value ? InterviewType.video : "phone" in value ? InterviewType.phone : "inPerson" in value ? InterviewType.inPerson : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    paused: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "open" in value ? JobStatus.open : "paused" in value ? JobStatus.paused : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interview>): Array<Interview> {
    return value.map((x)=>from_candid_Interview_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobOpening>): Array<JobOpening> {
    return value.map((x)=>from_candid_JobOpening_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CandidateStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandidateStatus): _CandidateStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_EntityStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityStatus): _EntityStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): _InterviewStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewType): _InterviewType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandidateStatus): {
    new: null;
} | {
    placed: null;
} | {
    screening: null;
} | {
    rejected: null;
} | {
    interviewing: null;
} | {
    offered: null;
} {
    return value == CandidateStatus.new ? {
        new_: null
    } : value == CandidateStatus.placed ? {
        placed: null
    } : value == CandidateStatus.screening ? {
        screening: null
    } : value == CandidateStatus.rejected ? {
        rejected: null
    } : value == CandidateStatus.interviewing ? {
        interviewing: null
    } : value == CandidateStatus.offered ? {
        offered: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == EntityStatus.active ? {
        active: null
    } : value == EntityStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): {
    scheduled: null;
} | {
    noShow: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == InterviewStatus.scheduled ? {
        scheduled: null
    } : value == InterviewStatus.noShow ? {
        noShow: null
    } : value == InterviewStatus.cancelled ? {
        cancelled: null
    } : value == InterviewStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    closed: null;
} | {
    open: null;
} | {
    paused: null;
} {
    return value == JobStatus.closed ? {
        closed: null
    } : value == JobStatus.open ? {
        open: null
    } : value == JobStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewType): {
    video: null;
} | {
    phone: null;
} | {
    inPerson: null;
} {
    return value == InterviewType.video ? {
        video: null
    } : value == InterviewType.phone ? {
        phone: null
    } : value == InterviewType.inPerson ? {
        inPerson: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
